name: Update Aria2 EXE

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Läuft täglich um Mitternacht

jobs:
  update-exe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Download and unzip latest Aria2 release
        run: |
          echo "Downloading latest Aria2 win-64bit zip..."
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/aria2/aria2/releases/latest |
          jq -r '.assets[] | select(.name | test("win-64bit.*\\.zip")) | .browser_download_url')
          if [[ -z "$DOWNLOAD_URL" ]]; then
            echo "Download URL not found"
            exit 1
          fi
          wget -O aria2-win-64bit.zip "$DOWNLOAD_URL"
          unzip aria2-win-64bit.zip -d ./aria2-release

      - name: Find and store the path of the downloaded aria2c.exe
        run: |
          echo "Searching for aria2c.exe recursively..."
          ARIA2C_PATH=$(find ./aria2-release -name 'aria2c.exe' -print -quit)
          if [[ -z "$ARIA2C_PATH" ]]; then
            echo "aria2c.exe not found"
            exit 1
          fi
          echo "Found aria2c.exe at $ARIA2C_PATH"
          echo "ARIA2C_PATH=$ARIA2C_PATH" >> $GITHUB_ENV

      - name: Compare MD5 hashes and update if necessary
        run: |
          LOCAL_HASH=$(md5sum ./aria2c.exe | cut -d ' ' -f1)
          DOWNLOADED_HASH=$(md5sum ${{ env.ARIA2C_PATH }} | cut -d ' ' -f1)
      
          if [[ "$DOWNLOADED_HASH" != "$LOCAL_HASH" ]]; then
            echo "Newer version found. Uploading exe to GitHub..."
            mv ${{ env.ARIA2C_PATH }} ./aria2c.exe  # Überschreibe die lokale Datei
            git config --global user.email "ynexgaming@gmail.com"
            git config --global user.name "yNEX"
            git add aria2c.exe
            git commit -m "Update aria2 executable to latest version"
            git push origin HEAD:main
          else
            echo "No newer version found. Exiting without updating."
      